package com.ds.trainapplication.mapping;
// Generated Apr 8, 2019 9:29:15 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import com.ds.trainapplication.bean.AbstractTimestampEntity;


/**
 * Destination generated by hbm2java
 */
@Entity
@Table(name="destination"
    ,catalog="trainapplication"
)
public class Destination  extends AbstractTimestampEntity  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -8772273959201646746L;
	/**
	 * 
	 */
	
	private Integer id;
     private String name;

    public Destination() {
    }

    public Destination(String name) {
       this.name = name;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


