package com.ds.trainapplication.mapping;
// Generated Apr 8, 2019 9:29:15 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.ds.trainapplication.bean.AbstractTimestampEntity;
import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * Reservation generated by hbm2java
 */
@Entity
@Table(name = "reservation", catalog = "trainapplication")
public class Reservation extends AbstractTimestampEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1335043436296687503L;
	/**
	* 
	*/
	private Integer id;
	private Customer customer;
	private Date date;
	private Integer seatsReserved;
	private String receiptNumber;

	public Reservation() {
	}

	public Reservation(Customer customer) {
		this.customer = customer;
	}

	public Reservation(Customer customer, Date date, Integer seatsReserved, String receiptNumber) {
		this.customer = customer;
		this.date = date;
		this.seatsReserved = seatsReserved;
		this.receiptNumber = receiptNumber;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id", nullable = false)
	@JsonBackReference
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "seats_reserved")
	public Integer getSeatsReserved() {
		return this.seatsReserved;
	}

	public void setSeatsReserved(Integer seatsReserved) {
		this.seatsReserved = seatsReserved;
	}

	@Column(name = "receipt_number")
	public String getReceiptNumber() {
		return this.receiptNumber;
	}

	public void setReceiptNumber(String receiptNumber) {
		this.receiptNumber = receiptNumber;
	}

}
