package com.ds.trainapplication.mapping;
// Generated Apr 8, 2019 9:29:15 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

import com.ds.trainapplication.bean.AbstractTimestampEntity;


/**
 * SchedulestationId generated by hbm2java
 */
@Embeddable
public class SchedulestationId extends AbstractTimestampEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7900357737956684803L;
	/**
	* 
	*/
	
	private int id;
	private int stationId;

	public SchedulestationId() {
	}

	public SchedulestationId(int id, int stationId) {
		this.id = id;
		this.stationId = stationId;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "station_id", nullable = false)
	public int getStationId() {
		return this.stationId;
	}

	public void setStationId(int stationId) {
		this.stationId = stationId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SchedulestationId))
			return false;
		SchedulestationId castOther = (SchedulestationId) other;

		return (this.getId() == castOther.getId()) && (this.getStationId() == castOther.getStationId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getStationId();
		return result;
	}

}
