package com.ds.trainapplication.mapping;
// Generated Apr 8, 2019 9:29:15 PM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.ds.trainapplication.bean.AbstractTimestampEntity;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Station generated by hbm2java
 */
@Entity
@Table(name = "station", catalog = "trainapplication")
public class Station extends AbstractTimestampEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -9174627426284680025L;
	private Integer id;
	private String name;
	private Set<Schedulestation> schedulestations = new HashSet<Schedulestation>(0);

	public Station() {
	}

	public Station(String name, Set<Schedulestation> schedulestations) {
		this.name = name;
		this.schedulestations = schedulestations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "station")
	@JsonIgnore
	public Set<Schedulestation> getSchedulestations() {
		return this.schedulestations;
	}

	public void setSchedulestations(Set<Schedulestation> schedulestations) {
		this.schedulestations = schedulestations;
	}

}
