package com.ds.trainapplication.mapping;
// Generated Apr 8, 2019 9:29:15 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.ds.trainapplication.bean.AbstractTimestampEntity;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Traindetail generated by hbm2java
 */
@Entity
@Table(name = "traindetail", catalog = "trainapplication")
public class Traindetail extends AbstractTimestampEntity implements java.io.Serializable {

	/**
	* 
	*/
	private static final long serialVersionUID = 6191496554433501287L;
	/**
	 * 
	 */
	private Integer id;
	private Train train;
	private String origin;
	private String destination;
	private Integer totalNoOfSeats;
	private Double fairFirstClass;
	private Double fairSecondClass;
	private Double fairThirdClass;

	public Traindetail() {
	}

	public Traindetail(Train train) {
		this.train = train;
	}

	public Traindetail(Train train, String origin, String destination, Integer totalNoOfSeats, Double fairFirstClass,
			Double fairSecondClass, Double fairThirdClass) {
		this.train = train;
		this.origin = origin;
		this.destination = destination;
		this.totalNoOfSeats = totalNoOfSeats;
		this.fairFirstClass = fairFirstClass;
		this.fairSecondClass = fairSecondClass;
		this.fairThirdClass = fairThirdClass;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "train_id", nullable = false)
	@JsonIgnore
	public Train getTrain() {
		return this.train;
	}

	public void setTrain(Train train) {
		this.train = train;
	}

	@Column(name = "origin")
	public String getOrigin() {
		return this.origin;
	}

	public void setOrigin(String origin) {
		this.origin = origin;
	}

	@Column(name = "destination")
	public String getDestination() {
		return this.destination;
	}

	public void setDestination(String destination) {
		this.destination = destination;
	}

	@Column(name = "total_no_of_seats")
	public Integer getTotalNoOfSeats() {
		return this.totalNoOfSeats;
	}

	public void setTotalNoOfSeats(Integer totalNoOfSeats) {
		this.totalNoOfSeats = totalNoOfSeats;
	}

	@Column(name = "fair_first_class", precision = 22, scale = 0)
	public Double getFairFirstClass() {
		return this.fairFirstClass;
	}

	public void setFairFirstClass(Double fairFirstClass) {
		this.fairFirstClass = fairFirstClass;
	}

	@Column(name = "fair_second_class", precision = 22, scale = 0)
	public Double getFairSecondClass() {
		return this.fairSecondClass;
	}

	public void setFairSecondClass(Double fairSecondClass) {
		this.fairSecondClass = fairSecondClass;
	}

	@Column(name = "fair_third_class", precision = 22, scale = 0)
	public Double getFairThirdClass() {
		return this.fairThirdClass;
	}

	public void setFairThirdClass(Double fairThirdClass) {
		this.fairThirdClass = fairThirdClass;
	}

}
