package com.ds.trainapplication.mapping;
// Generated Apr 8, 2019 9:29:15 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.ds.trainapplication.bean.AbstractTimestampEntity;
import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * Train generated by hbm2java
 */
@Entity
@Table(name = "train", catalog = "trainapplication")
public class Train extends AbstractTimestampEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1173319031573546016L;
	/**
	* 
	*/
	
	private Integer id;
	private String trainNumber;
	private String trainName;
	private Set<Traindetail> traindetails = new HashSet<Traindetail>(0);
	private Set<TrainHasSchedulestation> trainHasSchedulestations = new HashSet<TrainHasSchedulestation>(0);
	private Set<Trainclass> trainclasses = new HashSet<Trainclass>(0);

	public Train() {
	}

	public Train(String trainNumber, String trainName, Set<Traindetail> traindetails,
			Set<TrainHasSchedulestation> trainHasSchedulestations, Set<Trainclass> trainclasses) {
		this.trainNumber = trainNumber;
		this.trainName = trainName;
		this.traindetails = traindetails;
		this.trainHasSchedulestations = trainHasSchedulestations;
		this.trainclasses = trainclasses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "train_number")
	public String getTrainNumber() {
		return this.trainNumber;
	}

	public void setTrainNumber(String trainNumber) {
		this.trainNumber = trainNumber;
	}

	@Column(name = "train_name")
	public String getTrainName() {
		return this.trainName;
	}

	public void setTrainName(String trainName) {
		this.trainName = trainName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "train")
	@JsonBackReference
	public Set<Traindetail> getTraindetails() {
		return this.traindetails;
	}

	public void setTraindetails(Set<Traindetail> traindetails) {
		this.traindetails = traindetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "train")
	@JsonBackReference
	public Set<TrainHasSchedulestation> getTrainHasSchedulestations() {
		return this.trainHasSchedulestations;
	}

	public void setTrainHasSchedulestations(Set<TrainHasSchedulestation> trainHasSchedulestations) {
		this.trainHasSchedulestations = trainHasSchedulestations;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "trainclass_has_train", catalog = "trainapplication", joinColumns = {
			@JoinColumn(name = "train_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "trainClass_id", nullable = false, updatable = false) })
	@JsonBackReference
	public Set<Trainclass> getTrainclasses() {
		return this.trainclasses;
	}

	public void setTrainclasses(Set<Trainclass> trainclasses) {
		this.trainclasses = trainclasses;
	}

}
