package com.ds.trainapplication.mapping;
// Generated Apr 8, 2019 9:29:15 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.ds.trainapplication.bean.AbstractTimestampEntity;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * TrainHasSchedulestation generated by hbm2java
 */
@Entity
@Table(name = "train_has_schedulestation", catalog = "trainapplication")
public class TrainHasSchedulestation extends AbstractTimestampEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8360492196474577026L;
	/**
	* 
	*/
	private TrainHasSchedulestationId id;
	private Schedulestation schedulestation;
	private Train train;
	private Integer operatingDays;

	public TrainHasSchedulestation() {
	}

	public TrainHasSchedulestation(TrainHasSchedulestationId id, Schedulestation schedulestation, Train train) {
		this.id = id;
		this.schedulestation = schedulestation;
		this.train = train;
	}

	public TrainHasSchedulestation(TrainHasSchedulestationId id, Schedulestation schedulestation, Train train,
			Integer operatingDays) {
		this.id = id;
		this.schedulestation = schedulestation;
		this.train = train;
		this.operatingDays = operatingDays;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "trainId", column = @Column(name = "train_id", nullable = false)),
			@AttributeOverride(name = "scheduleStationId", column = @Column(name = "scheduleStation_id", nullable = false)),
			@AttributeOverride(name = "scheduleStationStationId", column = @Column(name = "scheduleStation_station_id", nullable = false)) })
	public TrainHasSchedulestationId getId() {
		return this.id;
	}

	public void setId(TrainHasSchedulestationId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "scheduleStation_id", referencedColumnName = "id", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "scheduleStation_station_id", referencedColumnName = "station_id", nullable = false, insertable = false, updatable = false) })
	@JsonIgnore
	public Schedulestation getSchedulestation() {
		return this.schedulestation;
	}

	public void setSchedulestation(Schedulestation schedulestation) {
		this.schedulestation = schedulestation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "train_id", nullable = false, insertable = false, updatable = false)
	@JsonIgnore
	public Train getTrain() {
		return this.train;
	}

	public void setTrain(Train train) {
		this.train = train;
	}

	@Column(name = "operating_days")
	public Integer getOperatingDays() {
		return this.operatingDays;
	}

	public void setOperatingDays(Integer operatingDays) {
		this.operatingDays = operatingDays;
	}

}
